#!/usr/bin/ruby

# === EDITOR ===
Pry.editor = 'vi'

# == Pry-Nav - Using pry as a debugger ==
Pry.commands.alias_command 'c', 'continue' rescue nil
Pry.commands.alias_command 's', 'step' rescue nil
Pry.commands.alias_command 'n', 'next' rescue nil

# === History ===
Pry.config.history.file = File.expand_path('~/.history/ruby')

# === CUSTOM PROMPT ===
# This prompt shows the ruby version (useful for RVM)
prompt_proc = lambda do |obj, nest_level, _|
  ruby_info = ""
  ruby_info << "#{Rails.version}@" if defined?(Rails)
  ruby_info << RUBY_VERSION
  ruby_info = "\e[32m#{ruby_info}\e[0m"
  nest_info = "#{nest_level}"
  obj_info  = "\e[33m#{obj}\e[0m"
  "[#{ruby_info}] #{nest_info}:(#{obj_info}) > "
end

Pry.prompt = [prompt_proc, prompt_proc]

# === Listing config ===
# Better colors - by default the headings for methods are too
# similar to method name colors leading to a "soup"
# These colors are optimized for use with Solarized scheme
# for your terminal
Pry.config.ls.separator = "\n" # new lines between methods
Pry.config.ls.heading_color = :magenta
Pry.config.ls.public_method_color = :green
Pry.config.ls.protected_method_color = :yellow
Pry.config.ls.private_method_color = :bright_black