#!/usr/bin/ruby

if defined?(Pry)
  rails = File.join Dir.getwd, 'config', 'environment.rb'

  if File.exist?(rails) && ENV['SKIP_RAILS'].nil?
    require rails

    if Rails.version[0..0] == "2"
      require 'console_app'
      require 'console_with_helpers'
    elsif Rails.version[0..0] == "3"
      require 'rails/console/app'
      require 'rails/console/helpers'
    else
      warn "[WARN] cannot load Rails console commands (Not on Rails2 or Rails3?)"
    end
  end

  if defined?(Rails::ConsoleMethods)
    extend Rails::ConsoleMethods
  end
end

def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  ActiveRecord::Base.clear_active_connections!
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end

if defined?(Pry)
  show_log
end

# showing log by default
IRB.conf[:IRB_RC] = Proc.new do
  show_log
end