#!/usr/bin/env bash

ln -sf ~/dotfiles/.ackrc ~/.ackrc
ln -sf ~/dotfiles/.alias ~/.alias
ln -sf ~/dotfiles/.bashrc ~/.bashrc
ln -sf ~/dotfiles/.bash_profile ~/.bash_profile
ln -sf ~/dotfiles/.ctags ~/.ctags
ln -sf ~/dotfiles/.gemrc ~/.gemrc
ln -sf ~/dotfiles/.gitconfig ~/.gitconfig
ln -sf ~/dotfiles/.gitignore_global ~/.gitignore_global
ln -sf ~/dotfiles/.globalrc ~/.globalrc
ln -sf ~/dotfiles/.ideavimrc ~/.ideavimrc
ln -sf ~/dotfiles/.irbrc ~/.irbrc
ln -sf ~/dotfiles/.profile ~/.profile
ln -sf ~/dotfiles/.pryrc ~/.pryrc
ln -sf ~/dotfiles/.rdebugrc ~/.rdebugrc
ln -sf ~/dotfiles/.siegerc ~/.siegerc
ln -sf ~/dotfiles/.vimrc.after ~/.vimrc.after
ln -sf ~/dotfiles/.vimrc.before ~/.vimrc.before
ln -sf ~/dotfiles/.zshenv ~/.zshenv
ln -sf ~/dotfiles/.zshrc ~/.zshrc

# Emacs Doom
ln -sf ~/dotfiles/.doom.d ~/.doom.d

# Karabiner
mkdir -p ~/.config/karabiner
cp ~/dotfiles/karabiner.json ~/.config/karabiner/karabiner.json
